# Nom de l'application
spring:
  application:
    name: product-management-server


  datasource:
    url: jdbc:postgresql://localhost:5433/produits_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  # Configuration de JPA et Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
