services:
  product-management-db:
    image: postgres
    container_name: product-management-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=produits_db
    ports:
      - "5432:5432"
  product-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-management
    ports:
      - "8080:8080"