# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'shary'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-management:8080'] # Service name and port